---

version: '3.3'

services:
   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     volumes:
       - ../site/wp-content:/var/www/html/wp-content
       - ./setup/chown-wp-content.sh:/usr/local/bin/chown-wp-content.sh
       - ./setup/disable-plugins.sh:/usr/local/bin/disable-plugins.sh
     ports:
       - '80:80'
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: password
       WORDPRESS_TABLE_PREFIX: your_prefix_

   db:
     image: mysql:5.7
     volumes:
       - ./database:/var/lib/mysql
       - ./mysqldumps/backup.sql.gz:/docker-entrypoint-initdb.d/backup.sql.gz
       - ./migrate/migrate.sql:/docker-entrypoint-initdb.d/migrate.sql
     restart: always
     ports: 
       - '3306:3306'
     environment:
       MYSQL_ROOT_PASSWORD: password
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: password
